# Generated by Django 4.2.17 on 2024-12-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviciu', '0002_serviciu_pret'),
    ]

    operations = [
        migrations.CreateModel(
            name='programare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('ora', models.TimeField(verbose_name='Ora')),
                ('serviciu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programare', to='serviciu.serviciu')),
            ],
        ),
    ]
