# Generated by Django 4.2.17 on 2024-12-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciu',
            name='pret',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
